global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.Hosting;
global using System;
global using System.Linq;
global using Microsoft.Extensions.DependencyInjection;
global using System.Collections.Generic;
global using Microsoft.AspNetCore.Mvc;
global using System.Threading.Tasks;